env:
  global:
    - CC_TEST_REPORTER_ID=2209a595e594f7dee1b3e4eb41c6ccf19f3422d2c8ff000b72c93a37069335f8
    - SURGE_LOGIN=tasteful-trains.surge.sh
    - SURGE_TOKEN=3ef23c7c9f36b7cb53a00c60bc417d0d
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - yarn test --coverage
  - yarn run build
notifications:
  slack: onetwentyseven:SG7VLQ1eHC34T5B57kBRu1d2
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: tasteful-trains.surge.sh